openapi: 3.0.0
info:
  version: 0.0.1
  title: anonymous twitter API
servers:
  - url: 'http://localhost:3001'
paths:
  /tweets:
    post:
      summary: 'Create a new tweet'
      tags:
        - tweets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: this is the content for this tweet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                  status:
                    type: number
        '400': # status code
          description: Bad Request
        '404': # status code
          description: Cannot find any appropriate response
    get:
      summary: 'Query the top 10 tweets'
      tags:
        - tweets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  status:
                    type: number
        '400': # status code
          description: Bad Request
        '404': # status code
          description: Cannot find any appropriate response
  /tweets/retweet:
    post:
      summary: 'Retweet'
      tags:
        - tweets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                retweet_id:
                  type: string
                  example: tweet Id to retweet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                  status:
                    type: number
        '400': # status code
          description: Bad Request
        '404': # status code
          description: Cannot find any appropriate response
